# Generated by Django 4.0.4 on 2022-09-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField(verbose_name='text description')),
                ('title', models.TextField(verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('weight', models.IntegerField(default=10)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.section')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('weight', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.question')),
            ],
        ),
    ]
