# Generated by Django 4.0.4 on 2022-09-10 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_section_section_number_alter_option_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section_pt',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_number', models.IntegerField(default=1)),
                ('title', models.TextField(verbose_name='title')),
                ('desc', models.TextField(verbose_name='text description')),
            ],
        ),
        migrations.CreateModel(
            name='Question_pt',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('weight', models.IntegerField(default=10)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_pt', to='home.section')),
            ],
        ),
        migrations.CreateModel(
            name='Option_pt',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('weight', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_pt', to='home.question')),
            ],
        ),
    ]
