# Generated by Django 4.0.4 on 2022-09-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_section_pt_question_pt_option_pt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option_pt',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question_pt',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section_pt',
        ),
        migrations.AddField(
            model_name='option',
            name='text_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Text portugese'),
        ),
        migrations.AddField(
            model_name='section',
            name='desc_pt',
            field=models.TextField(blank=True, null=True, verbose_name='text description'),
        ),
        migrations.AddField(
            model_name='section',
            name='title_pt',
            field=models.TextField(blank=True, null=True, verbose_name='title'),
        ),
        migrations.DeleteModel(
            name='Option_pt',
        ),
        migrations.DeleteModel(
            name='Question_pt',
        ),
    ]
