# Generated by Django 4.0.4 on 2022-09-15 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_option_pt_question_remove_question_pt_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='desc_pt',
            field=models.TextField(blank=True, null=True, verbose_name='text description pt'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_pt',
            field=models.TextField(blank=True, null=True, verbose_name='title pt'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='home.response')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='home.section')),
            ],
        ),
    ]
