# Generated by Django 4.0.4 on 2022-09-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_response_alter_section_desc_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
