# Generated by Django 4.0.4 on 2022-09-29 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='home.response'),
        ),
    ]
